# Navigation
menu:
  Home:
    url: //www.rainmeter.net
    external: true
  Documentation:
    url: //docs.rainmeter.net
    external: true
  Discover:
    url: /discover/
    external: false
  Community:
    url: //forum.rainmeter.net/
    external: true

# Downloads
downloads:
  versionName: '4.5.13 Release'
  date: 'March 23, 2022'
  downloadURL: https://github.com/rainmeter/rainmeter/releases/download/v4.5.13.3632/Rainmeter-4.5.13.exe
  mirrorURL: https://builds.rainmeter.net/Rainmeter-4.5.13.exe
  releaseNotesURL: /changes-4.5
  enabled: true

# News block
news:
  - title: 'Rainmeter 4.5.13 Release'
    url: /changes-4.5
    date: 'March 23, 2022'
  - title: 'Need Help with Localization'
    url: /localization
    date: 'June 26, 2021'

# skin carousel
carousel:
  - link: https://github.com/khanhas/mnmlUI
    imageURL: img/skins/mnmlUI.png
    title: 'mnml UI'
    author: 'khanhas'
  - link: https://redsaph.deviantart.com/art/Cleartext-for-Rainmeter-519796161
    imageURL: img/skins/cleartext_by_redsaph.png
    title: 'Cleartext'
    author: 'Redsaph'
  - link: https://fuckyeahlucas.deviantart.com/art/Cloudy-Rainmeter-Skin-v1-7-590741555
    imageURL: img/skins/cloudy_by_fuckyeahlucas.png
    title: 'Cloudy'
    author: 'Lucas S'
  - link: https://hiphopium.deviantart.com/art/Realistic-Weather-Forecast-4-691768369
    imageURL: img/skins/realistic_weather_forecast_4__by_hiphopium.png
    title: 'Realistic Weather Forcast 4'
    author: 'hiphopium'
  - link: https://forum.rainmeter.net/viewtopic.php?f=27&t=34477#p170453
    imageURL: img/skins/textclock_2_1_by_jsmorley.png
    title: 'TextClock'
    author: 'JSMorley'
  - link: https://undefinist.deviantart.com/art/VisBubble-Round-Visualizer-for-Rainmeter-488601501
    imageURL: img/skins/visbubble_by_undefinist.png
    title: 'VisBubble'
    author: 'undefinist'

# Showcase gallery
gallery:
  - type: 'gfycat'
    link: https://www.reddit.com/r/Rainmeter/comments/5rg8fp/howling_atat/
    thumbnailURL: img/showcase/thumb_HowlingATAT.png
    content: BestInsecureHowlermonkey
    title: 'Howling AT-AT'
    author: 'Jumats'
  - type: 'image'
    link: https://hiphopium.deviantart.com/art/Momento-698402825
    thumbnailURL: img/showcase/thumb_momento.png
    content: img/showcase/momento.png
    title: 'Momento'
    author: 'HipHopium'
  - type: 'image'
    link: https://www.deviantart.com/art/Rime-Rainmeter-642132946
    thumbnailURL: img/showcase/thumb_rime.png
    content: img/showcase/rime.png
    title: 'Rime Rainmeter'
    author: 'Iroaseta'
  - type: 'image'
    link: https://www.reddit.com/r/Rainmeter/comments/60qz2m/cyberpunk_coffee/
    thumbnailURL: img/showcase/thumb_CyberpunkCoffee.png
    content: img/showcase/cyberpunkcoffee.gif
    title: 'Cyberpunk Coffee'
    author: 'Labr4t'
  - type: 'gfycat'
    link: https://www.reddit.com/r/Rainmeter/comments/5erns9/a_clean_daft_punk_setup_giving_life_back_to_music/
    thumbnailURL: img/showcase/thumb_cleanDaftPunk.png
    content: GreatShadyAegeancat
    title: 'Clean Daft Punk setup'
    author: 'The_siderian'
  - type: 'video'
    link: https://www.reddit.com/r/Rainmeter/comments/6fi83s/blue_and_simple/
    thumbnailURL: img/showcase/thumb_BlueAndSimple.png
    content: img/showcase/BlueAndSimple.mp4
    title: 'Blue and Simple'
    author: 'keeWend'
  - type: 'image'
    link: https://www.reddit.com/user/khanhas
    thumbnailURL: img/showcase/thumb_polybar.png
    content: img/showcase/polybar.png
    title: 'polybar'
    author: 'khanhas'
  - type: 'image'
    link: https://iroaseta.deviantart.com/art/Geometry-Rainmeter-666821772
    thumbnailURL: img/showcase/thumb_geometry.png
    content: img/showcase/geometry.png
    title: 'Geometry Rainmeter'
    author: 'Iroaseta'
  - type: 'gfycat'
    link: https://www.reddit.com/r/Rainmeter/comments/6gv77s/so_this_is_the_volume2_of_my_zelda_theme/
    thumbnailURL: img/showcase/thumb_ZeldaTheme2.png
    content: WelldocumentedGlossyAnkolewatusi
    title: 'Zelda theme 2.0'
    author: 'NicoNoFace'


# SASS configuration
sass:
  # debug: true
  # outputStyle: nested
  # precision: 5
  # sourceComments: false
  includePaths:
    - "./node_modules"
